version: '3.8'
services:

  pg-db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user_name
      POSTGRES_PASSWORD: password
      POSTGRES_DB: django_db
      
  library-app:
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/auth
  
  #Redis Service
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./:/var/www
      - ./docker/redis-data:/data

  #Celery Service
  celery:
    build:
      context: .
    command: celery --app auth worker --loglevel=info
    volumes:
      - ./:/auth
    depends_on:
      - redis

  #Celery beat Service
  celery-beat:
    build:
      context: .
    command: celery --app auth beat
    volumes:
      - ./:/auth
    depends_on:
      - redis

  # #Pyhton Service
  # challanger-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: python
  #   ports:
  #     - "80:5050"
  #   container_name: challanger
  #   restart: unless-stopped
  #   tty: true
  #   working_dir: /var/www
  #   volumes:
  #     - ./:/var/www
